name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Determine changed modules
      id: changed-modules
      run: |
        git fetch origin main
        CHANGED_MODULES=$(git diff --name-only origin/main | grep -E 'AccountsService|CustomersService' | xargs -I {} dirname {} | uniq)
        echo "CHANGED_MODULES=$CHANGED_MODULES" >> $GITHUB_ENV

    - name: Build changed modules
      run: |
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules changed."
        else
          for module in $CHANGED_MODULES; do
            echo "Building module: $module"
            mvn -pl $module clean install
          done
        fi

    - name: Verify build logs
      run: |
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules were built."
        else
          echo "Modules built: $CHANGED_MODULES"
        fi